export const columns = [
   {name: 'İSİM', uid: 'name'},
   {name: 'GÖREV', uid: 'role'},
   {name: 'DURUM', uid: 'status'},
   {name: 'İŞLEMLER', uid: 'actions'},
];
export const users = [
   {
      id: 1,
      name: 'Onur Korkmaz',
      role: 'Personel',
      team: 'Yönetim',
      status: 'Aktif',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'onur.korkmaz@test.com',
   },
   {
      id: 2,
      name: 'Fatma Develi',
      role: 'Personel',
      team: 'Yönetim',
      status: 'İzinli',
      age: '25',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
      email: 'fatma.develi@test.com',
   },
   {
      id: 3,
      name: 'Hanife Gül',
      role: 'Personel',
      team: 'Bordro ve Özlük İşleri',
      status: 'Aktif',
      age: '22',
      avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
      email: 'hanife.gul@example.com',
   },
   {
      id: 4,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Resmi_İzinli',
      age: '28',
      avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
      email: 'test.test@test.com',
   },
   {
      id: 5,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Aktif',
      age: '24',
      avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
      email: 'test.test@test.com',
   },
   {
      id: 6,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Aktif',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'test.test@test.com',
   },
   {
      id: 10,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Aktif',
      age: '24',
      avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
      email: 'test.test@test.com',
   },
   {
      id: 8,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Aktif',
      age: '22',
      avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
      email: 'test.test@test.com',
   },
   {
      id: 7,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'İzinli',
      age: '25',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
      email: 'test.test@test.com',
   },

   {
      id: 9,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Resmi_İzinli',
      age: '28',
      avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
      email: 'test.test@test.com',
   },
   {
      id: 11,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Aktif',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'test.test@test.com',
   },
   {
      id: 12,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Aktif',
      age: '24',
      avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
      email: 'test.test@test.com',
   },
   {
      id: 13,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Aktif',
      age: '22',
      avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
      email: 'test.test@test.com',
   },
   {
      id: 14,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'İzinli',
      age: '25',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
      email: 'test.test@test.com',
   },
   {
      id: 15,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Aktif',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'test.test@test.com',
   },
   {
      id: 16,
      name: 'Test Test',
      role: 'Personel',
      team: 'Memur',
      status: 'Aktif',
      age: '24',
      avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
      email: 'test.test@test.com',
   },
];
